apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: spiderman
  namespace: default
  description: Group of your local Peter Parkers
spec:
  type: team
  profile:
    displayName: spiderman
  children: []